# Generated by Django 2.2 on 2019-04-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='todo',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
