# Generated by Django 2.2 on 2019-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosbackend', '0002_auto_20190403_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='isDone',
            field=models.BooleanField(default=True),
        ),
    ]
